name: the
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: archive the source code to a jar file
      run: jar cfv the-mod.jar

    - name: Upload Mod Jar
      uses: actions/upload-artifact@v2
      with: 
        name: the-mod.jar
        path: *.jar
